version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pfee
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: farah
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: